export const demoPermissions = [
  "create_firm",
  "view-all-firms",
  "update_firm",
  "delete_firm",
  "create_lawyer",
  "read_lawyer",
  "update_lawyer",
  "delete_lawyer",
  "create_client",
  "read_client",
  "update_client",
  "delete_client",
  "create_case",
  "read_case",
  "update_case",
  "delete_case",
  "view_case_status",
  "update_case_status",
  "assign_lawyer_to_case",
  "view_case_documents",
  "upload_case_document",
  "delete_case_document",
  "view_stats",
  "assign_role",
  "create_role",
  "view_role",
];

export const demoPermissionRecords = demoPermissions.map((name, index) => ({
  id: index + 1,
  name,
  createdAt: "2026-01-05T09:00:00.000Z",
  updatedAt: "2026-01-05T09:00:00.000Z",
}));
